const userdata = {
  firstname: "Robert",
  lastname: "Zhang",
  resultdata: [
    {
      experimentName: "rule1",
      created: 1592592287,
      numATClusters: 41,
      trained: true,
      numRuleClusters: 15,
    },
    {
      experimentName: "rule2",
      created: 1593582287,
      numATClusters: 9,
      trained: true,
      numRuleClusters: 10,
    },
    {
      experimentName: "rule3",
      created: 1592782287,
      numATClusters: 28,
      trained: true,
      numRuleClusters: 5,
    },
    {
      experimentName: "rule4",
      created: 1592732287,
      numATClusters: 14,
      trained: false,
      numRuleClusters: 3,
    },
    {
      experimentName: "rule5",
      created: 1592702287,
      numATClusters: 36,
      trained: true,
      numRuleClusters: 13,
    },
    {
      experimentName: "rule6",
      created: 1592712287,
      numATClusters: 4,
      trained: true,
      numRuleClusters: 12,
    },
    {
      experimentName: "rule7",
      created: 1512782287,
      numATClusters: 29,
      trained: true,
      numRuleClusters: 14,
    },
    {
      experimentName: "rule8",
      created: 1592722287,
      numATClusters: 24,
      trained: false,
      numRuleClusters: 9,
    },
    {
      experimentName: "rule9",
      created: 1592742287,
      numATClusters: 25,
      trained: true,
      numRuleClusters: 12,
    },
    {
      experimentName: "rule10",
      created: 1592582287,
      numATClusters: 39,
      trained: false,
      numRuleClusters: 14,
    },
    {
      experimentName: "rule11",
      created: 1591782287,
      numATClusters: 9,
      trained: true,
      numRuleClusters: 10,
    },
    {
      experimentName: "rule12",
      created: 1562782287,
      numATClusters: 36,
      trained: false,
      numRuleClusters: 4,
    },
    {
      experimentName: "rule13",
      created: 1572782287,
      numATClusters: 40,
      trained: true,
      numRuleClusters: 13,
    },
  ],
};

export default userdata;
